apiVersion: v1
kind: Secret
metadata:
  name: {{ template "shibboleth.fullname" . }}
  labels:
    app: {{ template "shibboleth.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- range $key, $value := .Values.apache.secretEnvs }}
  apache-{{ $key | replace "/" "-" }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- range $key, $value := .Values.apache.secretFiles }}
  apache-{{ $key | replace "/" "-" }}: {{ $value | b64enc | quote }}
  {{- end }}
